####################################
    #Parámetros globales
    #Ruta principal

ruta_ppal = '/home/automatizacion/atencion_a_clientes/'
ruta_historica = '/home/automatizacion/atencion_a_clientes/historico_ejecuciones'
archivo_exportado = 'resumen.xlsx'
usuario = "automatizacion"
password = "LMUW7qczz4JRbJAuV6nmv8HbW" 
host = "172.16.100.10" 
puerto = 3306
bd = 'atencion_clientes'
diccionario_cambios_nombres={"ASESORIAS":"","ASESORIA":"","SISTEGRA":"","PESV":"","SG":"",
                             "SST":"","ENERO":"","FEBRERO":"","MARZO":"","ABRIL":"",
                             "MAYO":"","JUNIO":"","JULIO":"","AGOSTO":"","SEPTIEMBRE":"",
                             "OCTUBRE":"","NOVIEMBRE":"","DICIEMBRE":"","(":"",
                             ")":"","-":"","_":"","[":"","]":"","{":"","}":"",
                             ",":"",".":"","/":"","!":"","1CASTROTCHERASSI":"CASTROTCHERASSI",
                             #En este caso debemos primero hacer el reemplazo por el nombre recortado y 
                             # luego todos los que tengan el nombre recortado devolverlos al nombre completo 
                             # de la empresa. Para evitar corregir valores que tenían el nombre correcto.
                             "ACEROS CASETAS Y CONSTRUCCIONES SAS":"ACEROS Y CASETAS",
                             "ACEROS Y CASETAS":"ACEROS CASETAS Y CONSTRUCCIONES SAS",
                             "AIRE SMART SAS":"AIRE SMART","AIRE SMART":"AIRE SMART SAS",
                             "AIRE SMART S A S":"AIRE SMART SAS",
                             "AGENCIA DE ADUANAS ASIMCOMEX SAS NIVEL 1":"AGENCIA DE ADUANAS",
                             "AGENCIA DE ADUANAS":"AGENCIA DE ADUANAS ASIMCOMEX SAS NIVEL 1",
                             "EN SEGURIDAD Y SALUD EN EL TRABAJO":"","CLIENTE NUEVO":"",
                             "DISTRIAROMAS DE COLOMBIA SAS":"DISTRIAROMAS","DISTRIAROMAS":"DISTRIAROMAS DE COLOMBIA SAS",
                             "EKIRAA DISTRIBUCIONES SAS":"EKIRAA","EKIRAA":"EKIRAA DISTRIBUCIONES SAS",
                             "EXPERTOS IP":"EXPERTO IP","EXPERTO IP":"EXPERTOS IP","FREUVER DEL CAMPO":"FRUVER DEL CAMPO",
                             "G I GLOBAL INDUSTRIAL LTDA":"G I GLOBAL INDUSTRIAL","G I GLOBAL INDUSTRIAL":"G I GLOBAL INDUSTRIAL LTDA",
                             "HIDRAULICA Y SELLADOS LTDA":"HIDRAULICA Y SELLADOS","HIDRAULICA Y SELLADOS":"HIDRAULICA Y SELLADOS LTDA",
                             "IMQUIRURJICOS":"IMQUIRURGICOS SAS","INTERSERVIS LTDA":"INTERSERVIS",
                              "INTERSERVIS":"INTERSERVIS LTDA","INVERSIONES PLUS LS SAS":"INVERSIONES PLUS LS",
                              "INVERSIONES PLUS LS":"INVERSIONES PLUS LS SAS","MACIZO TEC SAS":"MACIZO TEC",
                              "MACIZO TEC":"MACIZO TEC SAS","MERKUR GAMING":"MERKUR",
                              "MERKUR GAMING COLOMBIA SAS":"MERKUR","MERKUR":"MERKUR GAMING COLOMBIA SAS",
                              "MONET REPROGRAMACION":"MONET COLOMBIA SAS","CADA 15 DIAS":"",
                              "REUNION SEMANAL":"","SERVICIO DE GRUA Y TALLER LOS ESPECIALISTAS MULTIMARCAS":"SERVICIO DE GRUA Y TALLER LOS ESPECIALISTAS",
                              "SERVICIO DE GRUA Y TALLER LOS ESPECIALISTAS":"SERVICIO DE GRUA Y TALLER LOS ESPECIALISTAS MULTIMARCAS",
                              "SERVICIOS DOCUMENTALES SAS":"SERVICIOS DOCUMENTALES","SERVICIOS DOCUMENTALES":"SERVICIOS DOCUMENTALES SAS",
                              "AGENCIA SIERRA SEGUROS":"AGENCIA SIERRA","AGENCIA SIERRA":"AGENCIA SIERRA SEGUROS",
                              "TECHNICE SERVICE":"TECHNIC SERVICE","TECHNISERVICE":"TECHNIC SERVICE","SOLAIR  PLUS":"SOLAIR",
                              "SOLAIR":"SOLAIR PLUS","SUMMARED":"SUMMA RED SAS","SYTCERCO SERVICIOS Y TALENTO CERTIFICADO DE LA COSTA SAS":"SYTCERCO",
                              "SYTCERCO":"SYTCERCO SERVICIOS Y TALENTO CERTIFICADO DE LA COSTA SAS","TALENTO CONSULTORES":"",
                              "TECHNIC SERVICE LTDA":"TECHNIC SERVICE","TECHNIC SERVICE":"TECHNIC SERVICE LTDA",
                              "TECHNOLOGY AND SISTEMS INDUSTRIES SAS":"TECHNOLOGY AND SYSTEMS","TECHNOLOGY AND SISTEMS":"TECHNOLOGY AND SYSTEMS INDUSTRIES SAS",
                              "TRANSPORTE SEGURO ESPECIALIZADO SAS":"TRANSPORTE SEGURO ESPECIALIZADO",
                              "TRANSPORTE SEGURO ESPECIALIZADO":"TRANSPORTE SEGURO ESPECIALIZADO SAS","TRANSPORTES ONIKA EXPRESS SAS":"TRANSPORTES ONIKA",
                              "TRANSPORTES ONIKA":"TRANSPORTES ONIKA EXPRESS SAS","TRANSPORTES QE ASEOSRIA":"TRANSPORTES QE SAS",
                              "UNIDAD OSTEOPOROSIS":"UNIDAD DE OSTEOPOROSIS SAS","AIRE SMART SAS S A S":"AIRE SMART SAS",
                              "ASASORIA":"","ASEORIA":"","ASESORIE":"","ASEOSRIA":"","ASESRIA":"",
                              "BIOPLUS MEDICAL CARE SAS":"BIOPLUS","BIOPLUS":"BIOPLUS MEDICAL CARE SAS",
                              "CALZAEMPRESAS SAS":"CALZAEMPRESAS","CALZAEMPRESAS":"CALZAEMPRESAS SAS","REUNION INICIAL":"",
                              "TRANSPORTANDO AM LOGISTICA INTEGRAL SAS":"TRANSPORTANDO AM","TRANSPORTANDO AM":"TRANSPORTANDO AM LOGISTICA INTEGRAL SAS",
                              "TRANSPORTES URBANO RIONEGRO SA":"TRANSPORTES URBANO RIONEGRO","TRANSPORTES URBANO RIONEGRO":"TRANSPORTES URBANO RIONEGRO SA",
                              "CORPORACION CLUB CAMPESTRE DE PEREIRA":"CLUB CAMPESTRE DE PEREIRA","CLUB CAMPESTRE DE PEREIRA":"CORPORACION CLUB CAMPESTRE DE PEREIRA",
                              "COMPANIA MINERA COLOMBO DE CARBON":"COMPANIA MINERA COLOMBO AMERICANA DE CARBON SAS",
                              "IMPACT HUB SAS":"FUNDACION IMPACT HUB","INDISTRIAS CHEMICAL SUPERIOR SAS":"INDUSTRIAS CHEMICAL SUPERIOR SAS",
                              "AMERICAN ROLLERS":"LABORAL AMERICAN ROLLER","REUNION DE DIAGNOSTICO LOPETRANS SAS":"LOPETRANS SAS",
                              "VIRTUAL A EMPRESA AWAKE DANIELA RAMIREZ":"AWAKE DANIELA RAMIREZ","VIRTUAL EMPRESA AWAKE DANIELA RAMIREZ":"AWAKE DANIELA RAMIREZ",
                              "VIRTUAL A DROGUERIA SAPAQ MIRANDA":"DROGUERIA SAPAQ","VIRTUAL EMPRESA DROGUERIA SAPAQ":"DROGUERIA SAPAQ",
                              "2025":"","2 CONEXION URANTUS GREENHOUSES SAS":"URANTUS GREENHOUSES SAS","APARCAMOTOS LA CANDELARIA SAS":"APARCAMOTOS LA CANDELARIA",
                              "APARCAMOTOS LA CANDELARIA":"APARCAMOTOS LA CANDELARIA SAS",
                              "DE CONSULTORES PROFESIONALES Y ACTUARIALES":"CONSULTORES PROFESIONALES Y ACTUARIALES LTDA",
                              "CONTRUCCION CON CONCIENCIA SAS":"CONSTRUCCION CON CONCIENCIA SAS",
                              "REPROGRAMACION CORRESPONDIENTE AL VIERNES INDUSTRIAS FERMEN":"INDUSTRIAS FERMEN",
                              "REPROGRAMACION CORRESPONDIENTE AL140425 GLOBAL EVEREST SAS":"GLOBAL EVEREST SAS",
                              "DROGAS LOS PAISASOS":"LOS PAISASOS","LOS PAISASOS":"DROGAS LOS PAISASOS",
                              "RAFAEL ANGEL ALVAREZ LONDONO FRUTAS Y VERDURAS SELECCIONADAS":"FRUTAS Y VERDURAS SELECCIONADAS SAS",
                              "REPROGRAMACION CORRESPONDIENTE AL VIERNES SANTO E3CREATIC":"E3CREATIC SAS",
                              "REUNION CALAMO":"CALAMO SAS","SMAT HEALT SAS":"SMART HEALT SAS","EMPRESA AWAKE VIRTUAL DANIELA RAMIREZ":"AWAKE DANIELA RAMIREZ",
                              "A EMPRESA AWEKE VIRTUAL":"AWAKE DANIELA RAMIREZ","TU PSICOLOGA CRISTIANA":"TU PSICOLOGA CRISTIANA SAS",
                              "A EMPRESA AWAKE DANIELA RAMIREZ":"AWAKE DANIELA RAMIREZ","A EMPRESA DROGUERIA SAPAQ MIRANDA":"DROGUERIA SAPAQ",
                              "EMPRESA VIRTUAL DROGUERIA SAPAQ":"DROGUERIA SAPAQ",
                              "A EMPRESA IEGENTHALER & CO S A S PAULA MARTINEZ":"VIRTUAL EMPRESA SIEGENTHALER & CO S A S",
                              "ANA MARIA CAMPUZANO ARBOLEDA":"ANA MARIA CAMPUZANO","ANA MARIA CAMPUZANO":"ANA MARIA CAMPUZANO ARBOLEDA",
                              "BIENVENIDA EMTURPE LIMITADA":"REUNION EMTURPE LIMITADA","BPO CONSULTORES":"BPO CONSULTORES SAS Y ALTERNOVA TECH SAS",
                              "CAPETRANS":"TRANSPORTES CAPETRANS","EXPERTOSIP":"EXPERTOS IP","SAFETY EXPORT SAS":"SAFETY EXPORT",
                              "SAFETY EXPORT":"SAFETY EXPORT SAS","TECHNIC SERVICE LTDA SAS":"TECHNIC SERVICE LTDA",
                              "TECHNIC SERVICE LTDA":"TECHNIC SERVICE LTDA SAS","TU PSICOLOGA CRISTIANA SAS SAS":"TU PSICOLOGA CRISTIANA SAS"
                             }
diccionario_reemplazos_nombres={"DB":"DBSOFT SAS","TRAZADO":"TRAZADO INMOBILIARIO","LONA":"LONA GROUP",
                                "EDS":"EDS LA PERLA","A+G CONSULTING":"AG CONSULTING SAS",
                                "TRANSPORTES QE":"TRANSPORTES QE SAS","DE PANIFICADORA MIPAN COLOMBIA":"DE PANIFICADORA MIPAN COLOMBIA SAS",
                                "PLATAFORMA INOVA":"28 INOVA","YARUMOS":"ED YARUMOS","TAMESIS":"EDS TAMESIS",
                                "TRT":"INVERSIONES TRT","DASAULT":"DASSAULT","EXTRA ACUAMANTIC":"GRUPO ACUAMATIC SAS",
                                "ALUMINIOS DE ANTIOQUIA":"ALUMINIOS Y VIDRIOS DE ANTIOQUIA"
                                }